name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e4fc7cfb194c9d4d506f8c17d90da7b55b7a2b360257aeadef8781e861cef47"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
