name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2238adc942b63619f115fadee1b1fe4253c44f098d90ebd70695475c1a1e07d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
