name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47d2886e09b6e95da0eae26939b17ffaba52847f4353d7dbc40b0978ec78ea9d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
unsup = "1.1.4"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
