name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56049b7f47fe79426ca53aa6ac9d487cf48d9323004d0d808836e4ff49427b5b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
