name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c8686893d8104ddb91e14bc38f2d01cdd71f5b788ebea2005bc261a1f041b4e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
