name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00ebacf1dbe352985ba98a4e6e15d5761c55fa741dfd55af727f8cbecc904371"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
