name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1fbba1434fcab843e00ace9ac2bed73467c5b083ef36f3a32b28e8bd10011f6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
