name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a3d646845fa5822f4107166840b83c021d16c8d00ff45134111652b89a7339"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
