name = "Minecraft Relaunch"
author = "Leialoha"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "111962e0f5ae5d021f3693904dd866567817ef269094a7324599ec64e1567588"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
unsup = "1.0.2"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/paxi/datapacks"
