[flavor_groups.rendering_mod]
name = "Rendering Mod"
description = "Which rendering mod you'd like to use.\nIncreases or decreases performance depending on choices."
side = "client"

[[flavor_groups.rendering_mod.choices]]
id = "no_rendering_mods"
name = "None"
description = "No rendering mods."

[[flavor_groups.rendering_mod.choices]]
id = "embeddium"
name = "Embeddium"
description = "Installs Embeddium and Iris, increasing performance and providing support for shaderpacks.\n<i>* Includes additional bugfixes & features for better mod compatibility</i>"

[[flavor_groups.rendering_mod.choices]]
id = "sodium"
name = "Sodium"
description = "Installs Sodium and Iris, increasing performance and providing support for shaderpacks."


[flavor_groups.recipe_mod]
name = "Recipe Veiwer Mod"
description = "Which recipe veiwer mod you'd like to use."
side = "client"

[[flavor_groups.recipe_mod.choices]]
id = "jei"
name = "JEI"
description = "Installs JustEnoughItems, showing the base recipes and that's all."

[[flavor_groups.recipe_mod.choices]]
id = "rei"
name = "REI"
description = "Installs RoughlyEnoughItems, creates item groups for recipes."

[[flavor_groups.recipe_mod.choices]]
id = "emi"
name = "EMI"
description = "Installs JustEnoughItems and EMI, quicker at registering and baking models."


[metafile.embeddium]
flavors = ["iris", "embeddium", "monocle-iris"]
[metafile.sodium]
flavors = ["iris", "sodium"]

[metafile.jei]
flavors = ["jei"]
[metafile.rei]
flavors = ["rei"]
[metafile.emi]
flavors = ["jei", "emi"]
